;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; High-level bindings for the IVRCompositor API.

;;;IVR_Compositor_022

(in-package 3b-openvr)

(defun submit (eye texture &key (compositor *compositor*)
                                (default-p t)
                                (lens-distortion-already-applied-p nil)
                                (gl-render-buffer-p nil)
                                (texture-with-pose-p nil)
                                (texture-with-depth-p nil)
                                (color-space :gamma)
                                (texture-type :open-gl)
                                (texture-bounds nil))
  (cffi:with-foreign-objects ((texture-pointer '(:struct texture-t))
                              (bounds-pointer '(:struct vr-texture-bounds-t))
                              (handle-pointer :int))
    (setf (cffi:mem-aref handle-pointer :int) texture)
    (let ((flags 0))
      (unless default-p 
        (when lens-distortion-already-applied-p (setf flags (logior flags 1)))
        (when gl-render-buffer-p (setf flags (logior flags 2)))
        (when texture-with-pose-p (setf flags (logior flags 8)))
        (when texture-with-depth-p (setf flags (logior flags 16))))
      (when texture-bounds
        (setf (cffi:mem-ref bounds-pointer '(:struct vr-texture-bounds-t)) texture-bounds))
      (let ((space color-space)) ; ugly.
        (cffi:with-foreign-slots ((handle type color-space) texture-pointer (:struct texture-t))
          (setf type texture-type
                handle (cffi:make-pointer texture)
                color-space space)))
     ; (break)
      (%submit (table compositor)
               eye
               texture-pointer
               (if texture-bounds bounds-pointer (cffi:null-pointer))
               flags))))

(defun wait-get-poses  (pose-array game-pose-array
                        &key (compositor *compositor*))
  (cffi:with-foreign-objects ((ppa '(:struct tracked-device-pose-t)
                                   (length pose-array))
                              (pgpa '(:struct tracked-device-pose-t)
                                    (length game-pose-array)))
    (check-ret
     (%wait-get-poses (table compositor)
                      (if pose-array ppa (null-pointer))
                      (length pose-array)
                      (if game-pose-array pgpa (null-pointer))
                      (length game-pose-array)))
    (loop for i below (length pose-array)
          for p = (cffi:mem-aptr ppa '(:struct tracked-device-pose-t) i)
          do (setf (aref pose-array i)
                   (when (cffi:foreign-slot-value p '(:struct tracked-device-pose-t) 'pose-is-valid)
                     (cffi:mem-ref p '(:struct tracked-device-pose-t)))))
    (loop for i below (length game-pose-array)
          for p = (cffi:mem-aptr pgpa '(:struct tracked-device-pose-t) i)
          do (setf (aref game-pose-array i) (cffi:mem-ref p '(:struct tracked-device-pose-t))))))

(defun get-last-pose (tracked-device &key (compositor *compositor*))
  (cffi:with-foreign-objects
      ((output-pose-pointer '(:struct tracked-device-pose-t))
       (output-game-pose-pointer '(:struct tracked-device-pose-t)))
    (%get-last-pose-for-tracked-device-index
     (table compositor)
     (tracked-device-index tracked-device)
     output-pose-pointer
     output-game-pose-pointer)
    (values (cffi:mem-ref output-pose-pointer '(:struct tracked-device-pose-t))
            (cffi:mem-ref output-game-pose-pointer '(:struct tracked-device-pose-t)))))

(define-clos-wrapper (compositor-frame-timing compositor-frame-timing) ()
                     ((size size)
                      (frame-index frame-index)
                      (number-of-times-presented num-frame-presents)
                      (number-of-times-mispresented num-mis-presented)
                      (number-of-times-dropped num-dropped-frames)
                      (reprojection-flags reprojection-flags)
                      (system-time system-time-in-seconds)
                      (pre-submit-gpu-duration pre-submit-gpu-ms)
                      (post-submit-gpu-duration post-submit-gpu-ms)
                      (total-render-gpu-duration total-render-gpu-ms)
                      (render-cpu-duration compositor-render-cpu-ms)
                      (render-gpu-duration compositor-render-gpu-ms)
                      (idle-duration compositor-idle-cpu-ms)
                      (client-frame-interval client-frame-interval-ms)
                      (present-call-cpu-duration present-call-cpu-ms)
                      (wait-for-present-duration wait-for-present-cpu-ms)
                      (submit-frame-duration submit-frame-ms)
                      (wait-get-poses-time wait-get-poses-called-ms)
                      (new-poses-ready-time new-poses-ready-ms)
                      (new-frame-ready-time new-frame-ready-ms)
                      (compositor-update-start-time compositor-update-start-ms)
                      (compositor-update-end-time compositor-update-end-ms)
                      (compositor-render-start-time compositor-render-start-ms)
                      (hmd-pose hmd-pose)
                      (number-of-vsyncs-ready-to-use num-vsyncs-ready-for-use)
                      (number-of-vsyncs-to-first-view num-vsyncs-to-first-view)))

(defun frame-timing (frames-ago &key (compositor *compositor*))
  (cffi:with-foreign-object (timing-pointer '(:struct compositor-frame-timing))
    (cffi:with-foreign-slots ((size) timing-pointer (:struct compositor-frame-timing))
      (setf size (cffi:foreign-type-size 'compositor-frame-timing-tclass)))
    (%get-frame-timing (table compositor) timing-pointer frames-ago)
    (cffi:mem-ref timing-pointer '(:struct compositor-frame-timing))))

(defun frame-timings (number-of-frames &key (compositor *compositor*))
  (cffi:with-foreign-object (timing-pointer '(:struct compositor-frame-timing) number-of-frames)
    (cffi:with-foreign-slots ((size) timing-pointer (:struct compositor-frame-timing))
      (setf size (cffi:foreign-type-size 'compositor-frame-timing-tclass)))
    (%get-frame-timings (table compositor) timing-pointer number-of-frames)))

(define-clos-wrapper (cumulative-statistics compositor-cumulative-stats) ()
                     ((pid pid)
                      (number-of-frames-presented num-frame-presents)
                      (number-of-frames-dropped num-dropped-frames)
                      (number-of-frames-reprojected num-reprojected-frames)
                      (number-of-frames-presented-on-startup num-frame-presents-on-startup)
                      (number-of-frames-dropped-on-startup num-dropped-frames-on-startup)
                      (number-of-frames-reprojected-on-startup num-reprojected-frames-on-startup)
                      (number-of-frames-loading num-loading)
                      (number-of-frames-presented-loading num-frame-presents-loading)
                      (number-of-frames-dropped-loading num-dropped-frames-loading)
                      (number-of-frames-reprojected-loading num-reprojected-frames-loading)
                      (number-of-frames-timed-out num-timed-out)
                      (number-of-frames-presented-timed-out num-frame-presents-timed-out)
                      (number-of-frames-dropped-timed-out num-dropped-frames-timed-out)
                      (number-of-frames-reprojected-timed-out num-reprojected-frames-timed-out)))

(defun cumulative-stats (&key (compositor *compositor*))
  (cffi:with-foreign-object (stats-pointer '(:struct compositor-cumulative-stats))
    (%get-cumulative-stats (table compositor)
                           stats-pointer
                           (cffi:foreign-type-size 'compositor-cumulative-stats-tclass))
    (cffi:mem-ref stats-pointer '(:struct compositor-cumulative-stats))))


(defun fade-color (&key (background-p nil) (compositor *compositor*))
  (let ((pointer (%get-current-fade-color (table compositor) background-p)))
    (cffi:with-foreign-slots ((r g b a) pointer (:struct hmd-color-t))
      (values r g b a))))

(defun override-skybox (textures &key (compositor *compositor*))
  (error "implement me"))
