(defpackage 3b-openvr
  (:use #:cl)
  (:import-from #:cffi
                #:DEFCENUM
                #:DEFCFUN
                #:DEFCTYPE
                #:DEFCSTRUCT
                #:DEFCUNION
                #:DEFBITFIELD
                #:NULL-POINTER
                #:FOREIGN-FUNCALL-POINTER)
  
  ;; applications.lisp
  (:export
   #:add-application-manifest
   #:scene-application-state
   #:application-property
   #:application-process-id
   #:application-keys
   #:current-scene-process-id)
  ;; chaperone.lisp
  (:export
   #:calibration-state
   #:play-area-size
   #:play-area-rect
   #:reload-chaperone-info
   #:bounds-visible-p
   #:force-bounds-visible)
  ;; chaperone-setup.lisp
  (:export
   #:commit-working-copy
   #:revert-working-copy
   #:working-play-area-size
   #:working-play-area-rect
   #:working-collision-bounds-info
   #:live-collision-bounds-info
   #:working-seated-zero-pose-to-raw-tracking-pose
   #:working-standing-zero-pose-to-raw-tracking-pose
   #:set-working-play-area-size
   #:set-working-collision-bounds-info
   #:set-working-perimeter
   #:set-working-seated-zero-pose-to-raw-tracking-pose
   #:set-working-standing-zero-pose-to-raw-tracking-pose
   #:reload-from-disk
   #:live-seated-zero-pose-to-raw-tracking-pose
   #:export-live
   #:import-to-working
   #:show-working-set-preview
   #:hide-working-set-preview
   #:room-setup-starting)
  ;; clos.lisp
  ;; compositor.lisp
  (:export
   #:submit
   #:wait-get-poses
   #:get-last-pose
   #:frame-timing
   #:frame-timings
   #:cumulative-stats
   #:tracking-space
   #:clear-last-submitted-frame
   #:post-present-handoff
   #:frame-time-remaining
   #:fade-to-color
   #:fade-grid
   #:grid-alpha
   #:clear-skybox-override
   #:bring-to-front
   #:go-to-back
   #:current-scene-focus-process
   #:last-frame-renderer
   #:can-render-scene-p
   #:dump-images
   #:should-app-render-with-low-resources-p
   #:force-interleaved-reprojection
   #:force-reconnect-process
   #:suspend-rendering
   #:mirror-gl-texture
   #:submit-explicit-timing-data
   #:motion-smoothing-enabled-p
   #:motion-smoothing-supported-p
   #:current-scene-focus-app-loading-p)
  ;;debug.lisp
  (:export
   #:emit-profiler-event
   #:begin-profiler-event
   #:finish-profiler-event
   #:driver-debug-request)
  ;;driver-manager.lisp
  (:export
   #:driver-count
   #:driver-name
   #:driver-names
   #:driver-handle
   #:driver-enabled-p)
  ;;extended-display.lisp
  (:export
   #:window-bounds
   #:eye-output-viewport)
  ;;headset-view.lisp
  (:export
   #:+headset-view-max-height+
   #:+headset-view-max-width+
   #:+headset-view-overlay-key+
   #:set-headset-view-size
   #:headset-view-size
   #:set-headset-view-mode
   #:headset-view-mode
   #:set-headset-view-cropped
   #:headset-view-cropped-p
   #:headset-view-aspect-ratio
   #:set-headset-view-blend-range
   #:headset-view-blend-range)
  ;;input.lisp
  (:export
   #:set-action-manifest-path
   #:action-set
   #:action
   #:input-source
   #:update-action-state
   #:digital-action-data
   #:analog-action-data
   #:pose-action-data-relative-to-now
   #:pose-action-data-for-next-frame
   #:bone-count
   #:bone-hierarchy
   #:bone-name
   #:trigger-haptic-vibration-action
   #:origin-tracked-device-information
   #:action-binding-information
   #:using-legacy-input-p
   #:action-data
   #:digital-action
   #:analog-action
   #:haptic-action
   #:pose-action
   #:skeletal-action
   #:bone)
  ;;io-buffer.lisp
  (:export
   #:io-buffer
   #:open-io-buffer
   #:close-io-buffer
   #:read-from-buffer
   #:write-to-buffer
   #:property-container
   #:has-readers-p)
  ;;library.lisp
  ;;low-level.lisp
  ;;notifications.lisp
  ;;overlay.lisp
  (:export
   #:find-overlay
   #:create-overlay
   #:destroy-overlay
   #:overlay-key)
  ;;pragma.lisp
  ;;render-models.lisp
  (:export
   )
  ;;resources.lisp
  (:export
   #:load-shared-resources
   #:resource-pathname)
  ;;screenshots.lisp
  (:export
   #:screenshot
   #:screenshot-from-handle
   #:request-screenshot
   #:hook-screenshot
   #:screenshot-property-type
   #:screenshot-property-filename
   #:update-screenshot-progress
   #:take-stereo-screenshot)
  ;;settings.lisp
  (:export
   #:remove-section
   #:remove-key-in-section
   #:settings-set
   #:settings-get)
  ;;spatial-anchors.lisp
  (:export
   )
  ;;system.lisp
  (:export
   )
  ;;tracked-camera.lisp
  (:export
   #:has-camera-p)
  ;;wrappers.lisp
  (:export
   #:vr-event
   #:vr-init
   #:with-vr
   #:vr-shutdown-internal
   #:vr-is-hmd-present
   #:vr-get-init-token
   #:vr-is-runtime-installed))
